version: "2.1"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:latest
    container_name: webtop
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: webtop_config
        target: /config
    ports:
      - 3000:3000
    shm_size: "2gb"
    restart: unless-stopped
volumes:
  webtop_config:
